Improved CLI
stateful/runme pull request #230
Opened 2023-04-30 02:07 UTC by christian-bromann

2023-05-02 12:50 UTC, sourishkrout commented
The scope of the original ticket https://github.com/stateful/runme/issues/229 is about changes, there wasn't green light for any other changes yet @christian-bromann.

2023-05-02 18:58 UTC, mxsdev requested changes
Really loving the UX changes, would love to see this implemented asap!

The runner-based implementation is also reasonable, though I do have some changes in mind. But the broad-strokes idea is good!

2023-05-02 18:58 UTC, mxsdev commented on internal/cmd/root.go
> +	pflags.BoolVar(&fIgnoreNameless, "ignore-nameless", true, "Ignore code blocks without name defined")
```suggestion
	pflags.BoolVar(&fIgnoreNameless, "ignore-nameless", false, "Ignore code blocks without name defined")
```

Should probably be false by default.

2023-05-02 18:58 UTC, mxsdev commented on internal/project/project.go
> +	root, err := os.Getwd()
```suggestion
	root := p.RootDir
```

2023-05-02 18:58 UTC, mxsdev commented on internal/project/project.go
> +	matches, err := fs.Glob(fsys, "**/*.md")
This [does not work](https://github.com/golang/go/issues/11862) as expected, and in particular will ignore files in the root directory.

You should probably use a `WalkDir`-based solution instead.

2023-05-02 18:58 UTC, mxsdev commented on internal/project/project.go
> +		codeBlock, err := p.GetCodeBlocks(file[len(p.RootDir):], false, true)
```suggestion
		codeBlock, err := p.GetCodeBlocks(file[len(p.RootDir):], allowUnknown, ignoreNameless)
```

Should pass these down

2023-05-02 18:58 UTC, mxsdev commented on internal/cmd/run.go
> +		fmt.Println("Interactive mode was disabled as it is not supported with the experimental CLI")
```suggestion
		fmt.Println("Interactivity was disabled as it is not supported with the experimental CLI")
```

2023-05-02 18:58 UTC, mxsdev commented on internal/cmd/run.go
> +		break
This break does nothing since there is no surrounding loop

2023-05-02 20:26 UTC, christian-bromann commented on internal/cmd/run.go
> +		cmd.Flags().BoolVarP(&onlyCommandIO, "onlyCommandOutput", "", false, "If set, Runme will only output command output. (experimental)")
Oh yeah totally! Nice

2023-05-18 18:26 UTC, christian-bromann commented
Closing in favor of #236

2023-05-18 18:26 UTC, closed without merging