(bugfix): support multiple categories
stateful/runme pull request #354
Opened 2023-07-28 23:01 UTC by christian-bromann

Given a user has the following markdown defined:

````md
```sh { name=a category=a }
echo "Category A"
```
```sh { name=b category=a,b }
echo "Category A,B"
```
```sh { name=c category=a,b,c }
echo "Category A,B,C"
```
````

If I currently run:

```sh
 ./runme run -c b
```

it returns:

```
No tasks to execute with the category provided
```

even though I expect the following:

```
Run 2 tasks for category b? [Y/n] Y

 ►  Running task b...
Category A,B
 ►  ✓ Task b exited with code 0
 ►  Running task c...
Category A,B,C
 ►  ✓ Task c exited with code 0
```

2023-07-31 22:21 UTC, sourishkrout requested changes
I'm fairly certain this change won't just work with the extension.

2023-07-31 23:29 UTC, christian-bromann commented
> I'm fairly certain this change won't just work with the extension.

Can you elaborate? This patch fixes a bug within the CLI when adding `-c` as category parameter. I also tested on the VS Code extension and it was able to run the example we have in the repository.

2023-08-01 19:59 UTC, sourishkrout commented
> > I'm fairly certain this change won't just work with the extension.
> 
> Can you elaborate? This patch fixes a bug within the CLI when adding `-c` as category parameter. I also tested on the VS Code extension and it was able to run the example we have in the repository.

What happens in the Notebook Runner when you assign multiple categories? Will the UI treat it as "a,b,c" or as "a", "b", "c"?

2023-08-01 21:51 UTC, christian-bromann commented
> What happens in the Notebook Runner when you assign multiple categories? Will the UI treat it as "a,b,c" or as "a", "b", "c"?

<img width="1093" alt="Screenshot 2023-08-01 at 14 47 44" src="https://github.com/stateful/runme/assets/731337/385d2232-4cb0-43ac-a908-f71f770c6dcc">

Apparently more as `ab`. According to the [docs](https://docs.runme.dev/configuration#run-all-cells-by-category)

````
```sh { category=category-two,category-two }
echo "Category one and two single line"
```
````

is a valid way to define a cell for two categories. I raised [an issue](https://github.com/stateful/vscode-runme/issues/733) for this some days ago as part of this investigation which I can tackle and fix as well.

2023-08-01 22:21 UTC, sourishkrout commented
Yes, please. We want both to work consistently.

2023-08-01 22:24 UTC, christian-bromann commented
> Yes, please. We want both to work consistently.

On it! I think we can move forward with this PR (merge and release) since the CLI feature is not connected with how runme is integrated in VS Code.

2023-08-03 17:12 UTC, merged