(docs): minor structural updates to the contributing doc
stateful/runme pull request #356
Opened 2023-07-31 17:00 UTC by christian-bromann

Minor structural updates to better follow the development lifecycle: setup > build > testing > release

I wonder if we still need the WASM part or if we can remove it? Anyway, that would be part of a different PR.

2023-07-31 20:45 UTC, sourishkrout commented
> I wonder if we still need the WASM part or if we can remove it? Anyway, that would be part of a different PR.

There's a ticket to remove it from the extension first, which is a precursor. It's ok to keep it in place for now.

2023-07-31 20:46 UTC, sourishkrout commented
Should most steps reference target's in the Makefile @christian-bromann?

2023-07-31 20:46 UTC, sourishkrout requested changes
See last comment.

2023-07-31 23:40 UTC, christian-bromann commented
> Should most steps reference target's in the Makefile @christian-bromann?

Sorry, I am not entirely sure what you mean by that. If you are suggesting to transform calls like `pre-commit run --files */**` into e.g. `make precommit` or `brew bundle --no-lock` into `make bundle`, I am totally open to that. I pushed a commit to replace the `go test` call with `make test`

2023-08-01 19:59 UTC, sourishkrout approved these changes
👍 LGTM

2023-08-01 20:03 UTC, merged