Replicate Environment Variable Resolution/Prompting like the current integration with the Extension
stateful/runme pull request #550
Opened 2024-04-08 12:46 UTC by pastuxso

TODO: Desecription

2024-04-08 17:54 UTC, pastuxso commented on internal/cmd/run.go
> +				defer localRunner.Stop()
It's required to stop the Ad-Hoc gRPC server

2024-04-08 17:55 UTC, pastuxso commented on internal/cmd/common.go
> +		if !block.PromptEnv() {
Refactor in favor of an early return instead of a nested block

2024-04-12 13:59 UTC, sourishkrout requested changes
See in-code comment. We also don't want to redo session mgmt for the clients either.

2024-04-12 13:59 UTC, sourishkrout commented on internal/runner/client/client_local.go
> +func (r *LocalRunner) setupAdHocServer() (
We want to extend the existing [Runner interface](https://github.com/stateful/runme/blob/main/internal/runner/client/client.go#L55-L66) that separates Local and Remote implementations, not make the Local implementation Remote.

2024-04-22 12:55 UTC, closed without merging