internal/document: improve attrs processing
stateful/runme pull request #74
Opened 2022-12-08 17:04 UTC by adambabik

Highlights:
- Remove serializing the `name` attribute if it was not present in the source.
- Add spaces between `{ ... }`.
-

2022-12-08 22:04 UTC, sourishkrout commented
I might need to introduce an identifier on the extension side that allows me to identify a cell (might just use xid). What do you think about excluding metadata keys starting with `_` (eg `_id`) from serialization? Simplifies managing transient metadata

2022-12-09 08:14 UTC, adambabik commented
@sourishkrout of course, we can exclude internal/private attributes. I was thinking either of `_` or `runme.dev/attribute-name`.

2022-12-09 15:45 UTC, sourishkrout commented
> @sourishkrout of course, we can exclude internal/private attributes. I was thinking either of `_` or `runme.dev/*`.
> 
> Let me know which way you want to go.

What do you think is cleaner? I'd like to avoid the metadata schema growing like weeds.

2022-12-09 15:50 UTC, adambabik commented
@sourishkrout if `_` is unused by VS Code, we can use `_` as it's shorter. If `_` is already used and we want to have more control then `runme.dev/*`.

2022-12-11 16:35 UTC, sourishkrout commented
> @sourishkrout if `_` is unused by VS Code, we can use `_` as it's shorter. If `_` is already used and we want to have more control then `runme.dev/*`.

Worked through the requirement for a ephemeral metadata attributes and turns out I can get around it using the native vscode API. However, I think we should probably jut do both `_` and `runme.dev/*` and choose depending on use-case which one is more appropriate.

Also, please go ahead and remove `index` entirely from the metadata. It's no longer required since the extension is relying exclusively on the API now.

2022-12-11 16:36 UTC, sourishkrout requested changes
Please see previous comment. Otherwise, ready to merge 👍 .

2022-12-12 11:25 UTC, merged